Q1. What are the benefits of the built-in array package, if any?

There are many benefits of the built-in array package like:
    
    Arrays are the direct way of acccessing data from memory 
    
    Memory allocation is in contiguous memory locations so, no chance of extra memory being allocated
    
    They are much more fast and efficient
    
    We can use many built-in methods on array like len(), append(), extend() which will make our work easier
    
    Type conversion is easier from array to list etc
    
    We can get the type code of the array as with which we can determine the elements inside array
    
    We can manipulate the index in arrays

Q2. What are some of the array package's limitations?

Limitations:
    
    The number of elements should be given and known before usage
    
    Arrays are static in nature so the size is fixed hence changing in runtime is tough
    
    The memory allocated is fixed so cannot be extended
    
    Wastage of memory can also happen if the elements are not fully utilized

Q3. Describe the main differences between the array and numpy packages.

Array:
    
    Arrays do not have any package to help with numerical calculations methods
    
    Arrays are single dimensional in nature
    
    Accessing, operations with respect to array elements are easier as we can just access elements with index

Numpy:
    
    Numpy provides, various numerical calculations methods and libraries which make the calculations easier

    Numpy can hold multi-dimensional data
    
    Accessing and operations on numpy elements are little complex as we have to access through row and column numbers
    
    These are faster in operations and render a greater performance and occupies lesser space

Q4. Explain the distinctions between the empty, ones, and zeros functions.

Empty Function

Some times an empty array is to be created which then can be filled with some other values, we can pass this array to avoid errors

So this can be considered as a dummy errors which then can be manipulated

Ones Function:
    
This function returns a array of given dimensions containing only every element as 1

Zeros Function:
    
This function returns a array of given dimensions containing only every element as 0

In [1]:
import numpy as np 
x = np.empty([2,2]) 
print (x)
y = np.zeros((2,2))  
print(y)  
z = np.ones((2,2))  
print(z)  

[[0. 0.]
 [0. 0.]]
[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]


Q5. In the fromfunction function, which is used to construct new arrays, what is the role of the callable argument?

The role of callable argument is to execute the function over every coordinate and the resulting array

The function is called with N parameters, N - is the rank of shape

Each parameter represents the coordinates of the array which vary among the axis

Q6. What happens when a numpy array is combined with a single-value operand (a scalar, such as an int or a floating-point value) through addition, as in the expression A + n?

When a numpy array is combined with a single-value operand such as an int or a floating-point value through addition, as in the expression A + n, then all the elements inside the array will add that value in it

Q7. Can array-to-scalar operations use combined operation-assign operators (such as += or *=)? What is the outcome?

Yes it will execute provided operation on all elements of the array

Q8. Does a numpy array contain fixed-length strings? What happens if you allocate a longer string to one of these arrays?

Yes, a numpy array contain fixed-length strings. The datatype of any numpy array containing string values with the maximum length of any string present in the array.

Now it will be able to store new string length not more than the maximum length at the time of creation

If we reassign some other value having greater length then it discards all the values exceed, the maximum length accept upto those are under limit

Q9. What happens when you combine two numpy arrays using an operation like addition (+) or multiplication (*)? What are the conditions for combining two numpy arrays?

When we combine two numpy arrays using an operation like addition (+) or multiplication (*) it will simply add or multiply element to element at same position

Q10. What is the best way to use a Boolean array to mask another array?

The best way to use a Boolean array to mask another array is by using masked_where of numpy package

Q11. What are three different ways to get the standard deviation of a wide collection of data using both standard Python and its packages? Sort the three of them by how quickly they execute.

1.np.std

2.stdev

3.math package

In [3]:
import numpy as np
arr = [20, 2, 7, 1, 34]
print("arr : ", arr) 
print("std of arr : ", np.std(arr))
print ("\nMore precision with float32")
print("std of arr : ", np.std(arr, dtype = np.float32))

import statistics
sample = [1, 2, 3, 4, 5]
print("Standard Deviation of sample is % s "% (statistics.stdev(sample)))

import math
import sys
def sd_calc(data):
    n = len(data)
    if n <= 1:
        return 0.0
    mean, sd = statistics.mean(data), 0.0
    for el in data:
        sd += (float(el) - mean)**2
    sd = math.sqrt(sd / float(n-1))
    return sd
data = [4, 2, 5, 8, 6]
print("Sample Data: ",data)
print("Standard Deviation : ",sd_calc(data))


arr :  [20, 2, 7, 1, 34]
std of arr :  12.576167937809991

More precision with float32
std of arr :  12.576168
Standard Deviation of sample is 1.5811388300841898 
Sample Data:  [4, 2, 5, 8, 6]
Standard Deviation :  2.23606797749979


Q12. What is the dimensionality of a Boolean mask-generated array?

The dimensionality of a Boolean mask-generated array will be same as the dimensionality as input array